"""
services/transaction_history.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Shared Transaction History Service — used by both the user-facing
profile screen (``handlers/main_menu.py``) and the admin User Control
Center (``admin_panel/user_control.py``).

Architecture
~~~~~~~~~~~~
  • Pure service layer — no router, no callback handlers, no FSM.
  • Provides two public functions:
      ``render_transaction_page()``  — fetch + format a paginated page
      ``build_transaction_keyboard()`` — build navigation inline keyboard
  • Callers (admin handler, user handler) import these functions and
    pass in a ``back_callback`` string to control where the "🔙 Back"
    button navigates — making this module fully reusable by both contexts.

Transaction Document Schema (from ``log_transaction``)::

    {
        "tx_id":      "<auto-generated Firestore doc ID>",
        "user_id":    "7437014244",
        "type":       "earn" | "spend" | "bonus" | "referral" | "compensation" | "refund",
        "amount":     500,
        "source":     "welcome_bonus" | "order_starter" | "admin_grant_123" | ...,
        "created_at": <datetime>,
    }
"""

from __future__ import annotations

import logging
from typing import Any

from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup

from instavault.database.db_manager import (
    count_user_transactions,
    get_user_transactions,
)
from instavault.utils.helpers import format_timestamp

logger = logging.getLogger(__name__)


# ===========================================================================
# CONSTANTS — Display Formatting
# ===========================================================================

# ── Transaction type → emoji + label ──────────────────────────────────────
_TX_TYPE_DISPLAY: dict[str, str] = {
    "earn": "🟢 Earned",
    "spend": "🔴 Spent",
    "bonus": "🎁 Bonus",
    "referral": "🤝 Referral",
    "compensation": "💰 Compensation",
    "refund": "🔄 Refund",
    "daily_free_bonus": "🎲 Daily Bonus",
}

# ── Source → human-readable label ─────────────────────────────────────────
# Only the most common sources are mapped; unknown sources are displayed
# as-is with title-casing.
_SOURCE_LABEL: dict[str, str] = {
    "welcome_bonus": "Welcome Bonus",
    "daily_mission": "Daily Mission",
    "shortener_mission": "Human Verification",
    "mystery_box": "Mystery Box",
    "referral_join": "Referral (Join Bonus)",
    "referral_mission": "Referral (Mission Bonus)",
    "referee_bonus": "Referee Welcome Bonus",
    "order_starter": "Order: Starter",
    "order_growth": "Order: Growth",
    "order_pro": "Order: Pro",
    "order_mega": "Order: Mega",
    "order_refund": "Order Refund",
}

_PAGE_SIZE = 8  # transactions per page (compact, fits in one screen)


# ===========================================================================
# §1  RENDERING — Format a single page of transaction history
# ===========================================================================


def _format_source(source: str) -> str:
    """Convert a raw source string to a human-readable label.

    Known sources are mapped to friendly names. Admin-originated sources
    (e.g. ``admin_grant_123456``) are formatted as "Admin Action".
    Unknown sources get title-cased.
    """
    if source in _SOURCE_LABEL:
        return _SOURCE_LABEL[source]
    if source.startswith("admin_"):
        return "⚙️ Admin Action"
    return source.replace("_", " ").title()


async def render_transaction_page(
    user_id: int | str,
    page: int = 0,
) -> tuple[str, int, int]:
    """Fetch and format a single page of transaction history.

    Args:
        user_id: Telegram user ID (or string representation).
        page: Zero-indexed page number.

    Returns:
        A 3-tuple of ``(formatted_text, total_transactions, total_pages)``.
        If the user has no transactions, ``formatted_text`` contains an
        empty-state message and both counts are ``0``.
    """
    total = await count_user_transactions(user_id)

    # ── Empty state ───────────────────────────────────────────────────────
    if total == 0:
        text = (
            "━━━━━━━━━━━━━━━━━━━━━━━\n"
            "💰 <b>TRANSACTION HISTORY</b>\n"
            "━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📭 No transactions found.\n\n"
            "<i>Transactions appear here when you earn or spend Sparks.</i>\n"
            "━━━━━━━━━━━━━━━━━━━━━━━"
        )
        return text, 0, 0

    # ── Pagination math ───────────────────────────────────────────────────
    total_pages = max(1, (total + _PAGE_SIZE - 1) // _PAGE_SIZE)
    page = max(0, min(page, total_pages - 1))

    # ── Fetch page from Firestore ─────────────────────────────────────────
    transactions = await get_user_transactions(
        user_id,
        limit=_PAGE_SIZE,
        page=page,
    )

    # ── Build formatted text ──────────────────────────────────────────────
    lines: list[str] = [
        "━━━━━━━━━━━━━━━━━━━━━━━",
        "💰 <b>TRANSACTION HISTORY</b>",
        f"<i>Page {page + 1}/{total_pages}  •  {total} total</i>",
        "━━━━━━━━━━━━━━━━━━━━━━━",
    ]

    for tx in transactions:
        tx_type = tx.get("type", "unknown")
        amount = int(tx.get("amount", 0))
        source = tx.get("source", "unknown")
        created = format_timestamp(tx.get("created_at"), fmt="%d %b %Y, %I:%M %p")

        # Type display with emoji
        type_display = _TX_TYPE_DISPLAY.get(tx_type, f"🔵 {tx_type.title()}")

        # Amount with sign: green (+) for inflows, red (−) for outflows
        if tx_type in ("spend",):
            amount_str = f"<b>−{amount:,}</b>"
        else:
            amount_str = f"<b>+{amount:,}</b>"

        # Human-readable source
        source_label = _format_source(source)

        lines += [
            "",
            f"{type_display}  •  {amount_str} ⚡",
            f"📋 {source_label}",
            f"🕐 {created}",
        ]

    lines.append("\n━━━━━━━━━━━━━━━━━━━━━━━")
    text = "\n".join(lines)

    return text, total, total_pages


# ===========================================================================
# §2  KEYBOARD — Pagination + contextual back button
# ===========================================================================


def build_transaction_keyboard(
    user_id: int | str,
    page: int,
    total_pages: int,
    back_callback: str,
    callback_prefix: str = "tx_page",
) -> InlineKeyboardMarkup:
    """Build the pagination + back keyboard for transaction history.

    Args:
        user_id: Target user ID (encoded in pagination callbacks).
        page: Current zero-indexed page.
        total_pages: Total number of pages.
        back_callback: Callback data for the "🔙 Back" button.
            - User context: ``"nav_profile"``
            - Admin context: ``"uc_profile:<uid>"``
        callback_prefix: Prefix for pagination callback data.
            - User context: ``"my_tx_page"``   → ``my_tx_page:<page>``
            - Admin context: ``"uc_tx_page"``  → ``uc_tx_page:<uid>:<page>``

    Returns:
        An ``InlineKeyboardMarkup`` with optional Prev/Next row and
        a back-navigation row.
    """
    rows: list[list[InlineKeyboardButton]] = []

    # ── Prev / Next navigation row ────────────────────────────────────────
    nav_row: list[InlineKeyboardButton] = []

    if page > 0:
        # Admin callbacks include user_id; user callbacks do not
        if callback_prefix == "my_tx_page":
            prev_data = f"{callback_prefix}:{page - 1}"
        else:
            prev_data = f"{callback_prefix}:{user_id}:{page - 1}"
        nav_row.append(InlineKeyboardButton(text="⬅️ Prev", callback_data=prev_data))

    if page < total_pages - 1:
        if callback_prefix == "my_tx_page":
            next_data = f"{callback_prefix}:{page + 1}"
        else:
            next_data = f"{callback_prefix}:{user_id}:{page + 1}"
        nav_row.append(InlineKeyboardButton(text="Next ➡️", callback_data=next_data))

    if nav_row:
        rows.append(nav_row)

    # ── Back button row ───────────────────────────────────────────────────
    rows.append([InlineKeyboardButton(text="🔙 Back", callback_data=back_callback)])

    return InlineKeyboardMarkup(inline_keyboard=rows)
